### ISSUE TITLE
OpenVAF cannot compile dc source example

### ISSUE THREAD

**Issue by ra3xdh** [pascalkuthe/OpenVAF#28]
It seems some branch contribution are not allowed. OpenVAF cannot compile DC source example from here: https://verilogams.com/tutorials/vloga-intro.html 

Here is the source file: 

~~~
`include "constants.vams"
`include "disciplines.vams"

module vdd (dd);
inout dd;
electrical dd;
parameter real dc=2.5;

analog V(dd) <+ dc;
endmodule
~~~

And here is the OpenVAF output:
~~~
$ /opt/openvaf/openvaf --version
openvaf 22.12.0
$ /opt/openvaf/openvaf vdd.va
thread '<unnamed>' panicked at 'internal error: entered unreachable code: attempted to read undefined value', openvaf/mir_llvm/src/builder.rs:112:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
~~~

**Comment by pascalkuthe** [comment]
Thank you for the bug report.

This issue was already reported in #22/#23 and has beem fixed on master. You can download the latest nightly build (link is on the readme) which includes the fix.
