### ISSUE TITLE
$display() causes a segmentation fault when invoked on windows

### ISSUE THREAD

**Issue by bertgoz** [pascalkuthe/OpenVAF#39]
Using openVAF 23_2_0 and Windows MSVC (with Desktop development C++ package) I obtain the following compilation error when using the $display function:

> error LNK2019: unresolved external symbol snprintf referenced in function cb.2

**Comment by dwarning** [comment]
It is similar to closed issue #35. Please try the nightly build from Readme in front.

**Comment by bertgoz** [comment]
Thanks, it now compiles but the nightly release is not compatible with ngspice-39

**Comment by dwarning** [comment]
Why?

Am 14.02.23 um 19:43 schrieb bertgoz:

**Comment by bertgoz** [comment]
I get "internal error -- segmentation violation" when running a circuit containing the compiled module with $display() in ngspice-39 Windows.

Without $display() the circuit runs fine (both in the openVAF official release and the nightly)

**Comment by pascalkuthe** [comment]
Thank your for reporting this bug. The same problem was already reported on the ngspice user forum.

The segmentation fault is windows specific and seems to be a problem with the way the C standard library works on windows. Sadly linking to the standard library (as a compiler) is a lot more challenging on windows (whereas the something is almost trivial on macos/linux).

I am actively working on the problem but its a bit challenging to solve.

**Comment by pascalkuthe** [comment]
thank you so much for digging into this. This does indeed seem to fix the problem. I was totally going in the wrong direction by looking at the standard library. There is simply so much complexity involved with targeting windows that I missed the obvious. The fact that getting any kind of debugging setup on windows in VM made this a pain to debug and I just put it off

**Comment by EternalXY** [comment]
:thumbsup:
