### ISSUE TITLE
ddt() outside of contribution statement

### ISSUE THREAD

**Issue by dwarning** [pascalkuthe/OpenVAF#80]
Is the application of the ddt() operator allowed outside of contribution statements?
E.g.:
taur = (3*qb)/(cbcj*ddt(vds));

openvaf is not complaining to this. LRM don't forbid this.

**Comment by pascalkuthe** [comment]
I will close this as I actually added a lot more testing here in #92. Its also a lot more optimal now and usually not require an extra internal node
