### ISSUE TITLE
elsif or elif?

### ISSUE THREAD

**Issue by dwarning** [pascalkuthe/OpenVAF#81]
LRM 2.4 Ch. 10.1 show directives

elsif

openvaf 23.5.0 seems to accept elif but not elsif

Maybe a bug.

**Comment by pascalkuthe** [comment]
yeah I think that's a typo, thanks! Fix in 3f6338b113765e7eb2bed65b651cad8108114a1c

**Comment by dwarning** [comment]
Many thanks.
Works like a charm.
